# Generated by Django 2.0.2 on 2020-09-03 07:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdcHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='主机名')),
                ('system', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统')),
                ('outernet_ip', models.CharField(max_length=32, verbose_name='外网ip')),
                ('intranet_ip', models.CharField(max_length=32, verbose_name='内网ip')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户')),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
                ('port', models.CharField(blank=True, max_length=32, null=True, verbose_name='端口')),
                ('ssh_port', models.CharField(blank=True, max_length=32, null=True, verbose_name='ssh端口')),
                ('status', models.IntegerField(choices=[(1, '启用'), (2, '禁用')], default=1, verbose_name='当前状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('lastlogintime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间')),
                ('nickname', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='拥有的所有角色')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'abstract': False,
            },
        ),
    ]
