# Generated by Django 2.0.2 on 2020-09-16 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_repo_sitedir_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idchost',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间'),
        ),
    ]
