# Generated by Django 2.0.2 on 2020-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200916_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='type',
            new_name='r_type',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='type',
            new_name='w_type',
        ),
        migrations.AlterField(
            model_name='repo',
            name='repoPassword',
            field=models.CharField(blank=True, max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='repoUser',
            field=models.CharField(blank=True, max_length=50, verbose_name='用户'),
        ),
    ]
