# Generated by Django 2.0.2 on 2020-09-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200917_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='r_type',
            new_name='rtype',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='w_type',
            new_name='wtype',
        ),
    ]
