# Generated by Django 3.1.1 on 2020-09-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200917_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='repoPassword',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='repoUser',
            field=models.CharField(max_length=50, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='rtype',
            field=models.CharField(choices=[('git', 'git'), ('svn', 'svn')], max_length=10, verbose_name='更新类型'),
        ),
        migrations.AlterField(
            model_name='website',
            name='wtype',
            field=models.CharField(choices=[('git', 'git'), ('svn', 'svn')], max_length=10, verbose_name='更新类型'),
        ),
    ]
