# Generated by Django 3.1.1 on 2020-09-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200921_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='repoPassword',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='repoUser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户'),
        ),
    ]
